# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pJgH-rYe-Mh8S6zdVojwf-YVjWLbFM27
"""

myList=[1,2,3,4,5,6,10,13,23,46,53,56]

def SwapHalfList(myList):
    S1=0
    S2=0
    L=len(myList)
    for i in range (L//2):
         S1 = S1+ myList[i]
    for i in range (L//2,L):
         S2 = S2+ myList[i] 
    for i in range (L//2):

      myList[i], myList[L//2+i]= myList[L//2+i], myList[i]
           

SwapHalfList(myList)


print(myList)

# Print even numbers in given range and enter the input
n =int(input("Input an integer : "))
start,end = 0, n

# iterating each number in list 

for num in range(start, end+1 ):  
    if num % 2 == 0: 
        print(num, end = " ")